name: Build and deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy
      uses: shalzz/zola-deploy-action@master
      env:
        BUILD_ONLY: true
        PAGES_BRANCH: gh-pages
    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
        repository-name: 'longfangsong/first-week-in-chalmers'
        branch: pages
        folder: public
        clean: true
        
